syntax = "proto3";

package pdf;

service PdfService {
  rpc GeneratePdf (PdfRequest) returns (PdfResponse);
  rpc GeneratePdfForAll (ForAllPdfRequest) returns (PdfResponse);
}

message PdfRequest {
  repeated string docName = 1;  
  optional bool landscape = 2;  
  optional bool zip = 3;        
  string html = 4;              // html markup encodeURIComponent
}

message ForAllPdfRequest {
  int32 docType = 1;           
  optional bool landscape = 2; 
  optional bool zip = 3;       
  string html = 4;             // html markup encodeURIComponent
}

message PdfResponse {
  string base64Data = 1; 
}