FROM ghcr.io/puppeteer/puppeteer:23.4.0

WORKDIR /app/pdf-service

# RUN git clone -b main https://github.com/oshuster/pdf-service.git .
RUN .

RUN mkdir -p logs && chmod -R 777 logs

ENV PORT=8180

RUN npm install

EXPOSE 8180

CMD ["npm", "start"]