FROM mcr.microsoft.com/playwright:v1.50.1-noble

ENV PORT=8180
ENV ENVIRONMENT=PRODUCTION
ENV ENVIRONMENT=debug

WORKDIR /app/pdf-service

RUN git clone --depth=1 -b optimization https://github.com/oshuster/pdf-service.git .

# RUN npm install
RUN npm install --omit=dev

EXPOSE 8180

CMD ["npm", "start"]