services:
  pdf-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: "pdf-service:${VERSION}"
    container_name: pdf-service
    ports:
      - 8180:8180
    restart: always
    volumes:
      - "/usr/local/servers/pdf-service/logs:/app/pdf-service/logs"
      - "/usr/local/servers/pdf-service/styles/acts:/app/pdf-service/styles/acts"
      - "/usr/local/servers/pdf-service/styles/documents:/app/pdf-service/styles/documents"
      - "/usr/local/servers/pdf-service/output:/app/pdf-service/output"
    environment:
      PORT: 8180
      LOG_LEVEL: "info"
      ENVIRONMENT: "PRODUCTION"
